import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Footer from './components/shared/Footer'
import Header from './components/shared/Header'
import './globals.css'

const montserrat = Montserrat({
	variable: '--font-geist-sans',
	subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
	title: 'Доставка грузов из Китая',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<head>
				<meta name='apple-mobile-web-app-title' content='SellerChina' />
			</head>
			<body className={`${montserrat.variable} antialiased`}>
				<Header />
				<main
					className='min-h-screen flex flex-col  items-center relative
        '
				>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	)
}
